# Generated by Django 3.2.12 on 2022-02-19 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChosenCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='Delete at')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='Delete at')),
                ('token_id', models.PositiveIntegerField(verbose_name='Token id')),
                ('image_2d', models.ImageField(upload_to='', verbose_name='Image 2d')),
                ('image_3d', models.ImageField(upload_to='', verbose_name='Image 3d')),
                ('speciality', models.CharField(choices=[('enhancer', 'Enhancer'), ('double_counter', 'Double counter'), ('magnet', 'Magnet'), ('counter_breaker', 'Counter breaker')], max_length=32, verbose_name='Speciality')),
                ('counter', models.PositiveIntegerField(verbose_name='Counter')),
                ('multiply_num', models.PositiveIntegerField(verbose_name='Multiply number')),
                ('sum_num', models.PositiveIntegerField(verbose_name='Sum number')),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('god', 'God')], max_length=32, verbose_name='Rarity')),
                ('blood', models.CharField(choices=[('zeos', 'Zeos')], max_length=32, verbose_name='Blood')),
                ('blood_portion', models.PositiveIntegerField(verbose_name='Blood portion')),
                ('is_upgraded', models.BooleanField(default=False, verbose_name='Is upgraded')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FullDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='Delete at')),
                ('deck_place', models.PositiveIntegerField(verbose_name='Deck place')),
                ('wallet', models.CharField(max_length=1024, verbose_name='Deck place')),
                ('nft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nft.nft', verbose_name='NFT')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
