version: "3.4"

services:
  backend:
    restart: always
    build:
      context: .
    environment:
      - DEBUG
      - SECRET_KEY
      - ALLOWED_HOSTS
      - CORS_ORIGIN_ALLOW_ALL
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    command: sh script/run.sh
    env_file: test.env
    volumes:
      - mediafiles:/app/project/media
  
  redis:
    restart: always
    image: redis:6.2.2-alpine

volumes:
  mediafiles:
    name: mediafiles
    external: true

networks:
  default:
    external:
      name: ddd_network