version: "3"

services:
  backend:
    build:
      context: .
    command: sh script/run.sh
    env_file: test.env
    volumes:
      - media-files:/app/project/media
  
  redis:
    image: redis:6.2.2-alpine

  postgres:
    image: postgres:14.1
    env_file: test.env
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
  media-files: