version: "3"

services:
  redis:
    image: redis:6.2.2-alpine
    ports:
      - '6379:6379'

  postgres:
    image: postgres:14.1
    env_file: dev.env
    ports:
      - "5443:5432"
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database: