# Generated by Django 3.2.12 on 2022-02-19 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='Delete at')),
                ('week_num', models.PositiveIntegerField(verbose_name='Week number')),
                ('day', models.CharField(choices=[('day_one', 'Day one'), ('day_two', 'Day two'), ('day_three', 'Day three'), ('day_four', 'Day four'), ('day_five', 'Day five'), ('day_six', 'Day six'), ('day_seven', 'Day seven')], max_length=60, verbose_name='Day')),
                ('game_num', models.PositiveIntegerField(verbose_name='Game number')),
                ('winner_wallet', models.CharField(max_length=1024, verbose_name='Winner wallet')),
                ('winner_prize', models.PositiveIntegerField(verbose_name='Winner prize')),
                ('eth_block_number', models.CharField(max_length=1024, verbose_name='Eth block number')),
                ('finished', models.BooleanField(default=False, verbose_name='Finished')),
                ('winner_nft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nft.nft', verbose_name='Winner nft')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
