# Generated by Django 3.2.12 on 2022-03-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0005_nft_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='speciality',
            field=models.CharField(choices=[('enhancer', 'Enhancer'), ('double_counter', 'Double counter'), ('magnet', 'Magnet'), ('counter_breaker', 'Counter breaker'), ('special_drop', 'Special drop'), ('nothing', 'Nothing')], max_length=32, verbose_name='Speciality'),
        ),
    ]
