# Generated by Django 3.2.12 on 2022-03-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0006_alter_nft_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='chosencard',
            name='total_counter',
            field=models.PositiveIntegerField(null=True, verbose_name='Total counter'),
        ),
    ]
