# Generated by Django 3.2.12 on 2022-03-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0007_chosencard_total_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulldeck',
            name='is_starter',
            field=models.BooleanField(default=False, verbose_name='Is starter'),
        ),
    ]
