# Generated by Django 3.2.12 on 2022-03-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0008_fulldeck_is_starter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chosencard',
            name='magnet_status',
            field=models.BooleanField(default=False, verbose_name='Magnet status'),
        ),
    ]
