# Generated by Django 3.2.12 on 2022-03-31 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0003_alter_round_day'),
        ('nft', '0009_chosencard_magnet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chosencard',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='round.round', verbose_name='Round'),
        ),
    ]
