# Generated by Django 3.2.12 on 2022-04-04 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0010_chosencard_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='chosencard',
            name='magnet_stole',
            field=models.BooleanField(default=False, verbose_name='Magnet status'),
        ),
    ]
