# Generated by Django 3.2.12 on 2022-05-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0011_chosencard_magnet_stole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chosencard',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Delete at'),
        ),
        migrations.AlterField(
            model_name='fulldeck',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Delete at'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Delete at'),
        ),
    ]
