# Generated by Django 3.2.12 on 2022-05-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0012_auto_20220512_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='blood',
            field=models.CharField(blank=True, choices=[('zeos', 'Zeos'), ('poseidon', 'Poseidon'), ('hades', 'Hades'), ('hestia', 'Hestia'), ('hera', 'Hera'), ('aphrodite', 'Aphrodite'), ('atena', 'Atena'), ('ares', 'Ares'), ('hermes', 'Hermes')], max_length=32, null=True, verbose_name='Blood'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='blood_portion',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Blood portion'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='counter',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Counter'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='image_2d',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image 2d'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='image_3d',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image 3d'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='multiply_num',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Multiply number'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='rarity',
            field=models.CharField(blank=True, choices=[('common', 'Common'), ('god', 'God')], max_length=32, null=True, verbose_name='Rarity'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='side',
            field=models.CharField(blank=True, choices=[('will', 'Will'), ('talent', 'Talent')], max_length=100, null=True, verbose_name='Side'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='speciality',
            field=models.CharField(blank=True, choices=[('enhancer', 'Enhancer'), ('double_counter', 'Double counter'), ('magnet', 'Magnet'), ('counter_breaker', 'Counter breaker'), ('special_drop', 'Special drop'), ('nothing', 'Nothing')], max_length=32, null=True, verbose_name='Speciality'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='sum_num',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Sum number'),
        ),
    ]
