# Generated by Django 3.2.12 on 2022-06-29 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0016_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nft',
        ),
        migrations.AddField(
            model_name='profile',
            name='nft',
            field=models.ManyToManyField(to='nft.NFT', verbose_name='NFT'),
        ),
    ]
