# Generated by Django 3.2.12 on 2022-02-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Whitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='Delete at')),
                ('nonce', models.PositiveIntegerField(verbose_name='nonce')),
                ('max_allowed_mint', models.PositiveIntegerField(verbose_name='Max allowed mint')),
                ('wallet', models.CharField(max_length=1024, verbose_name='Wallet')),
                ('signed_message', models.CharField(max_length=1024, verbose_name='Signed message')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
