# Generated by Django 3.2.12 on 2022-06-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitelist', '0002_alter_whitelist_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitelist',
            name='whitelist_type',
            field=models.CharField(choices=[('royal', 'Royal'), ('common', 'Common')], default='common', max_length=20, verbose_name='Whitelist type'),
        ),
    ]
