# Generated by Django 3.2.12 on 2022-02-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='Delete at')),
                ('chosen_counts', models.PositiveIntegerField(verbose_name='Chosen')),
                ('allow_upgrade', models.BooleanField(default=False, verbose_name='Allow upgrade')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
