# Generated by Django 3.2.12 on 2022-05-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='Delete at')),
                ('block_number', models.CharField(max_length=512, verbose_name='Block number')),
                ('from_address', models.CharField(max_length=1024, verbose_name='From address')),
                ('from_ens', models.CharField(blank=True, max_length=1024, null=True, verbose_name='From ENS')),
                ('to_address', models.CharField(max_length=1024, verbose_name='To address')),
                ('to_ens', models.CharField(blank=True, max_length=1024, null=True, verbose_name='To ENS')),
                ('tx_hash', models.CharField(max_length=1024, verbose_name='Transaction hash')),
                ('token_id', models.PositiveIntegerField(verbose_name='Token id')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
