# Generated by Django 3.2.12 on 2022-05-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_history', '0003_auto_20220512_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferhistory',
            name='analyzed',
            field=models.BooleanField(default=False, verbose_name='Analyzed'),
        ),
    ]
