# Generated by Django 3.2.12 on 2022-02-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='Delete at')),
                ('from_wallet', models.CharField(max_length=1024, verbose_name='From wallet')),
                ('to_wallet', models.CharField(max_length=1024, verbose_name='To wallet')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Amount')),
                ('unit', models.CharField(max_length=1024, verbose_name='Unit')),
                ('transaction_type', models.CharField(choices=[('send_money', 'Send money'), ('send_message', 'Send message')], max_length=100, verbose_name='Transaction type')),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed'), ('pending', 'Pending')], max_length=100, verbose_name='Status')),
                ('is_multi_sig', models.BooleanField(verbose_name='Is multi sig')),
                ('tx_id', models.CharField(max_length=1024, verbose_name='Tx id')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
