# Generated by Django 3.2.12 on 2022-03-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0002_auto_20220227_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='day',
            field=models.PositiveIntegerField(verbose_name='Day'),
        ),
    ]
