# Generated by Django 3.2.12 on 2022-05-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0003_alter_round_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Delete at'),
        ),
        migrations.AlterField(
            model_name='winner',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Delete at'),
        ),
    ]
